name: 'FPNet'
gpu_id: '0'

datasets_config:
  de_type:
    - SIDD
    # - GOPRO

 
  patch_size: 256
  num_worker_per_gpu: 8
  batch_size_per_gpu: 8
  datasets_root: ./option/Lin_datasets.yml

network_g:


  type: FPNAFNet
  width: 32
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]
  FGM_nums: 1
  backbone: NAFNet


train:
  optim_g:
    # type: AdamW
    lr: !!float 5e-4
    weight_decay: 0.
    betas: [0.9, 0.9]
  
  scheduler:
    # type: TrueCosineAnnealingLR
    T_max: 700000
    eta_min: !!float 1e-7
  
  total_iter: !!float 7e5
  warmup_iter: -1  # no warm up
  
  pixel_opt:
    type: L1Loss
    # loss_weight: 1
    # reduction: mean

val:
  val_freq: !!float 5e3
  metrics:
    PSNR: null
    SSIM: null

logger:
  print_freq: 200
  save_checkpoint: 
    interval: [!!float 5.5e5, !!float 6.5e5]
    freq : !!float 2500
