datasets_config:
  de_type:
    - SIDD
    # - GOPRO

  patch_size: 256
  num_worker_per_gpu: 2
  batch_size_per_gpu: 2
  datasets_root: .\option\win_datasets.yml


train:
  optim_g:
    lr: !!float 1e-3
    weight_decay: !!float 1e-4
    betas: [0.9, 0.9]


  scheduler:
    T_max: 1000
    eta_min: !!float 1e-7
  total_iter: 49
val:
  val_freq: !!float 2.5e1
  metrics:
    PSNR: null
    SSIM: null

